### ISSUE TITLE
Use `stable_deref_trait` instead of custom `StableBytes` trait

### ISSUE THREAD

**Issue by jdygert-spok** [rkyv/rkyv_util#4]
[`stable_deref_trait`](https://crates.io/crates/stable_deref_trait)'s [`StableDeref`](https://docs.rs/stable_deref_trait/1.2.0/stable_deref_trait/trait.StableDeref.html) seems to be the defacto standard way to express stable deref. I think it should be an easy swap, and will make `OwnedArchive` work for more third party container types, including `memmap2::Mmap`.

**Comment by jdygert-spok** [comment]
cc: @DiscordJim

**Comment by djkoloski** [comment]
`StableDeref` has [soundness problems](https://github.com/Storyyeller/stable_deref_trait/issues/15) because it provides impls for types which do not guarantee the properties it lists. We don't actually need most of those guarantees, but the wording on `StableBytes` could probably make this clearer. To contrast the two:

- `StableDeref` guarantees that `deref()` and `deref_mut()` can be cast to `*const` and `*mut`, held across non-mutating method calls (i.e. those which take `&self`), and then dereferenced safely
- `StableBytes` guarantees that every time you call `deref()` or `deref_mut()`, you get an equivalent slice of bytes.

`StableDeref` should not be implemented for `Box` or `&mut [u8]` because moving them (which is not a "mutating method call") invalidates the pointer (see thread for details). However, `StableBytes` can be implemented for `Box<[u8]>` because `Box` owns the bytes (so they won't get mutated out from under us) and it doesn't have a malicious impl per its API (`Box` always returns the same value from `deref`).

**Comment by jdygert-spok** [comment]
Oh I see, the requirements are actually different, in that we could implement `StableBytes` for e.g. an inline byte array. So soundness questions aside, we don't want `StableDeref` anyway.
